# Generated by Django 5.2.3 on 2025-06-25 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id_filial', models.AutoField(primary_key=True, serialize=False)),
                ('nome_cidade', models.CharField(max_length=100)),
                ('qtd_produtos', models.IntegerField(default=0)),
                ('empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.CASCADE, related_name='filiais', to='empresa.empresa')),
            ],
            options={
                'db_table': 'filial',
            },
        ),
    ]
