# Generated by Django 5.2.3 on 2025-06-24 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filial',
            name='qtd_produtos',
        ),
    ]
