# Generated by Django 5.2.3 on 2025-06-25 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('razao_social', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('qtd_filiais', models.IntegerField(default=0)),
                ('num_max_filiais', models.IntegerField()),
            ],
            options={
                'db_table': 'empresa',
            },
        ),
    ]
