# Generated by Django 5.2.3 on 2025-06-25 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentacao',
            fields=[
                ('indice', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quant', models.IntegerField()),
                ('descricao', models.TextField(blank=True, null=True)),
                ('peso', models.FloatField()),
                ('vegetariano', models.BooleanField()),
                ('filial', models.ForeignKey(db_column='id_filial', on_delete=django.db.models.deletion.CASCADE, related_name='alimentacoes', to='filial.filial')),
            ],
            options={
                'db_table': 'alimentacao',
            },
        ),
        migrations.CreateModel(
            name='UtilidadesDomesticas',
            fields=[
                ('indice', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quant', models.IntegerField()),
                ('descricao', models.TextField(blank=True, null=True)),
                ('material', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('caracteristicas', models.TextField()),
                ('filial', models.ForeignKey(db_column='id_filial', on_delete=django.db.models.deletion.CASCADE, related_name='utilidades_domesticas', to='filial.filial')),
            ],
            options={
                'db_table': 'utilidades_domesticas',
            },
        ),
        migrations.CreateModel(
            name='Vestuario',
            fields=[
                ('indice', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quant', models.IntegerField()),
                ('descricao', models.TextField(blank=True, null=True)),
                ('tamanho', models.IntegerField()),
                ('genero', models.CharField(max_length=20)),
                ('filial', models.ForeignKey(db_column='id_filial', on_delete=django.db.models.deletion.CASCADE, related_name='vestuarios', to='filial.filial')),
            ],
            options={
                'db_table': 'vestuario',
            },
        ),
    ]
